export type VodData = {
  id: string,
  stream_id?: string,
  user_id?: string,
  user_login?: string,
  user_name?: string,
  title: string,
  description?: string,
  created_at?: string,
  published_at?: string,
  url?: string,
  thumbnail_url?: string,
  viewable?: string,
  view_count?: number,
  language?: string,
  type?: string,
  duration: string,
  muted_segments?: any,
  hidden?: string,
}

export type ClipData = {
  id: string,
  url?: string,
  embed_url?: string,
  broadcaster_id?: string,
  broadcaster_name?: string,
  creator_id?: string,
  creator_name?: string,
  video_id?: string,
  game_id?: string,
  language?: string,
  title: string,
  view_count?: number,
  created_at: string,
  thumbnail_url: string,
  duration: number,
  hidden?: string,
}