import { gql } from 'apollo-server-micro'

export type TypeType = 'vod' | 'highlight' | 'clip'
export type VideoType = {
  id: string,
  title: string,
  duration: string,
  created: string,
  type: TypeType,
  videoUrl: string,
  subtitleUrl?: string,
  thumbnailUrl: string,
}
export type SelectorType = {
  id?: string,
  limit?: number,
  start?: string,
}
export type ResponseType = {
  insert?: VideoType[],
  videos: VideoType[],
  nextId?: string,
}
export type GetVideoProps = {
  type: TypeType,
  root: string,
  regex: RegExp,
}

export const typeDefs = gql`
  """
  A Video is a common object from vods, higlights, and clips.
  """
  type Video {
    """
    Internal ID generated by twitch, used as an ID.
    """
    id: String!
    """
    Title used by the creator.
    """
    title: String!
    """
    Length of the video, either in seconds (34) or labeled (1h2m3s).
    """
    duration: String!
    """
    Date when this video was created.
    """
    created: String!
    """
    Type: vod, highlight, or clip.
    """
    type: String!
    """
    URL of the video file.
    """
    videoUrl: String!
    """
    URL of the subtitle file, either a .json or a .ssa.br.
    """
    subtitleUrl: String
    """
    URL of the thumbnail file.
    """
    thumbnailUrl: String
  }
  """
  Selector allows specifying what and how much data to fetch.
  """
  input Selector {
    """
    ID of the first item to fetch.
    """
    id: String
    """
    Number of items to fetch.
    """
    limit: Int
    """
    Starting point for fetching previous items in 'insert' object.
    """
    start: String
  }
  """
  Response type of these endpoints.
  """
  type Response {
    """
    Results up to, not including the ID specified in Selector.start, if given.
    """
    insert: [Video]
    """
    Results of the query.
    """
    videos: [Video]!
    """
    Next available ID that was cut off by Selector.limit.
    """
    nextId: String
  }
  type Query {
    """
    Videos on Demand, every stream not explicitly taken down.
    """
    vods(selector: Selector): Response
    """
    Highlights uploaded by the streamer.
    """
    highlights(selector: Selector): Response
    """
    Clips made by viewers.
    """
    clips(selector: Selector): Response
  }
`